[package]
name = "rstu"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "main"
harness = false

[dependencies]

[dev-dependencies]
quickcheck = { version = "1.0.3" }
quickcheck_macros = { version = "1.0.0" }
criterion = { version = "0.5.1" }
rand = { version = "0.9.0" }
